### ISSUE TITLE
Error Connecting to Database

### ISSUE THREAD

**Issue by DanBonehill** [meat147/Point-of-Sale#10]
I get the following error when I try to run the app `connect ECONNREFUSED 127.0.0.1:27017`

This is because I can't connect to the database - mongodb://localhost/pizzakladow
Can we set up a MLab (MongoLab) database to connect to?

**Comment by DanBonehill** [comment]
I'm using C9 - I'll install mongo db in the environment and use the database in the repo. If I change the database I'd have to change it overtime I committed a change.

**Comment by meat147** [comment]
I will provide a config file for that later today.

**Comment by papajo** [comment]
hey Dan, make sure you're mongodb instance is running in the background..
