### ISSUE TITLE
Adress autocompletion

### ISSUE THREAD

**Issue by meat147** [meat147/Point-of-Sale#2]
https://developers.google.com/maps/documentation/javascript/places-autocomplete

http://localhost:3000/customers 
"neuer Kunde" Dialog
![](https://i.imgur.com/zzVwGd1.png)

**Comment by papajo** [comment]
I am working on this one.

**Comment by papajo** [comment]
Update - I am working on this issue.

**Comment by papajo** [comment]
It works on New Customer section. Will be now working on Edit Customer section.

**Comment by papajo** [comment]
Fixed the address search for edit customer modal too. Please check it out.

**Comment by meat147** [comment]
added with #12
