### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by meat147** [meat147/Point-of-Sale#9]
Navbar needs to be done

**Comment by meat147** [comment]
We need links to /products /customers as of now..

http://themes.getbootstrap.com/products/dashboard (i really like this one)

**Comment by DanBonehill** [comment]
Ok I'll work on that today then. So you want a horizontal navbar on the left side?

(I can't 'assign' this task to myself)

**Comment by meat147** [comment]
Well at first the normal top navbar would be okay but if you are up for the navbar to the left would be good.

**Comment by DanBonehill** [comment]
I'll do a top navbar first then swap it to a sidebar later on

**Comment by meat147** [comment]
Maybe we should consider a full css framework switch ? (maybe adminlte or similar)

https://almsaeedstudio.com/preview

@papajo @DanBonehill
